# ACP et LINUCB appliqués sur le jeux de données Cover-type

In [1]:
#importation des biblio
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import plotly.plotly as py
import plotly.graph_objs as go

In [2]:
# importation du jeux de données
dataset= pd.read_csv('/home/oaitichou/Téléchargements/covtype.csv')

-Contexte

Ce jeux de données contient des observations d'arbres de quatre zones de la forêt nationale de Roosevelt dans le Colorado. Toutes les observations sont des variables cartographiques de sections de forêt de 30 mètres sur 30 mètres. Il y a plus d'un demi million de mesures au total!


-Contenu

Ce jeux de données comprend des informations sur le type d'arbre, la couverture d'ombre, la distance aux sites d'intérêt à proximité (routes, etc.), le type de sol et la topographie locale.

In [3]:
dataset.head(5)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [5]:
dataset.describe()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,...,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000
mean,2959.365301,155.656807,14.103704,269.428217,46.418855,2350.146611,212.146049,223.318716,142.528263,1980.291226,...,0.090392,0.077716,0.002773,0.003255,0.000205,0.000513,0.026803,0.023762,0.015060,2.051471
std,279.984734,111.913721,7.488242,212.549356,58.295232,1559.254870,26.769889,19.768697,38.274529,1324.195210,...,0.286743,0.267725,0.052584,0.056957,0.014310,0.022641,0.161508,0.152307,0.121791,1.396504
min,1859.000000,0.000000,0.000000,0.000000,-173.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2809.000000,58.000000,9.000000,108.000000,7.000000,1106.000000,198.000000,213.000000,119.000000,1024.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,2996.000000,127.000000,13.000000,218.000000,30.000000,1997.000000,218.000000,226.000000,143.000000,1710.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,3163.000000,260.000000,18.000000,384.000000,69.000000,3328.000000,231.000000,237.000000,168.000000,2550.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
max,3858.000000,360.000000,66.000000,1397.000000,601.000000,7117.000000,254.000000,254.000000,254.000000,7173.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

In [4]:
labels = dataset["Cover_Type"]
donnees = dataset.drop(columns=["Cover_Type"])
donnees.head(4)
#altitude, pente, aspect

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,0

## Application de l'ACP

In [6]:
X = donnees.values         # transformer le dataset en matrice

sc = StandardScaler()     #instanciation de la standardisation

Z = sc.fit_transform(X)   #transformation–centrage-réduction
print(Z)

print(np.mean(Z))  #moyenne

print(np.std(Z,axis=0,ddof=0)) #écart-type

acp = PCA(svd_solver='full')  #instanciation de l'acp

/home/oaitichou/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning:

Data with input dtype int64 was converted to float64 by StandardScaler.

/home/oaitichou/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning:

Data with input dtype int64 was converted to float64 by StandardScaler.

[[-1.29780509 -0.93515698 -1.48281978 ... -0.16595612 -0.15601398
  -0.12365355]
 [-1.31923485 -0.89047967 -1.61636259 ... -0.16595612 -0.15601398
  -0.12365355]
 [-0.5549068  -0.14883628 -0.68156292 ... -0.16595612 -0.15601398
  -0.12365355]
 ...
 [-2.04784663  0.02987297  0.38677957 ... -0.16595612 -0.15601398
  -0.12365355]
 [-2.05498988  0.12816306  0.11969395 ... -0.16595612 -0.15601398
  -0.12365355]
 [-2.05856151  0.08348575 -0.14739167 ... -0.16595612 -0.15601398
  -0.12365355]]
1.9237296987811928e-17
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]

In [7]:
#calculs
coord = acp.fit_transform(Z)      # les coordonnees factorielles
print(acp.n_components_)         #nombre de composantes calculées

print(acp.explained_variance_)  #variance expliquée

eigval = acp.explained_variance_

#proportion de variance expliquée,l'info expliquee par les axes
print(acp.explained_variance_ratio_)

54
[3.69980049e+00 2.92060872e+00 2.39812651e+00 2.00298429e+00
 1.52108562e+00 1.46288583e+00 1.22850696e+00 1.16581934e+00
 1.10314659e+00 1.08425383e+00 1.07408896e+00 1.06742497e+00
 1.05475959e+00 1.03839150e+00 1.03634812e+00 1.03234408e+00
 1.02651259e+00 1.02458591e+00 1.02168640e+00 1.01645687e+00
 1.01431003e+00 1.01348390e+00 1.01026950e+00 1.00916096e+00
 1.00781285e+00 1.00656452e+00 1.00631467e+00 1.00438105e+00
 1.00413219e+00 1.00402842e+00 1.00376812e+00 1.00303562e+00
 1.00230668e+00 1.00124009e+00 1.00099775e+00 1.00074236e+00
 1.00046429e+00 1.00022879e+00 1.00001303e+00 9.79693760e-01
 8.25368884e-01 8.05878757e-01 6.43922342e-01 6.33859030e-01
 4.60319750e-01 4.15721936e-01 3.26885655e-01 2.88940993e-01
 2.51339648e-01 1.55695062e-01 1.36096410e-01 3.29870731e-03
 9.95185687e-30 2.08940070e-30]
[6.85147059e-02 5.40852536e-02 4.44096737e-02 3.70922378e-02
 2.81682037e-02 2.70904317e-02 2.27500897e-02 2.15892098e-02
 2.04286054e-02 2.00787401e-02 1.98905021e-02 1.97670951e-02
 1.95325514e-02 1.92294391e-02 1.91915987e-02 1.91174501e-02
 1.90094598e-02 1.89737804e-02 1.89200860e-02 1.88232431e-02
 1.87834867e-02 1.87681880e-02 1.87086622e-02 1.86881338e-02
 1.86631689e-02 1.86400516e-02 1.86354248e-02 1.85996171e-02
 1.85950085e-02 1.85930869e-02 1.85882665e-02 1.85747018e-02
 1.85612030e-02 1.85414513e-02 1.85369635e-02 1.85322340e-02
 1.85270846e-02 1.85227235e-02 1.85187280e-02 1.81424458e-02
 1.52845827e-02 1.49236550e-02 1.19244673e-02 1.17381100e-02
 8.52442515e-03 7.69854113e-03 6.05342764e-03 5.35074993e-03
 4.65442992e-03 2.88323692e-03 2.52029955e-03 6.10870672e-05
 1.84293329e-31 3.86925389e-32]

In [8]:
# Le critère du coude

mu = X.shape[1]
#plt.plot(np.arange(1,mu+1),eigval)
#plt.title("critère du coude")
#plt.ylabel("valeurs propres")
#plt.xlabel("nombre de facteurs")
#plt.show()


trace1 = go.Scatter(
    x= np.arange(1,mu+1),
    y= eigval
)
data = [trace1]
layout = dict(title = 'critère du coude',
              xaxis = dict(title = 'nombre de facteurs'),
              yaxis = dict(title = 'valeurs propres'),
              )
fig = dict(data=data, layout=layout)
py.iplot(fig, filename='styled-line')

/home/oaitichou/anaconda3/lib/python3.6/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead

In [9]:
#plt.plot(np.arange(1,mu+1),np.cumsum(acp.explained_variance_ratio_))
#plt.title("variance expliquée")
#plt.ylabel("ratio variance cumulée")
#plt.xlabel("nombre de facteurs")
#plt.show()

trace = go.Scatter(
    x= np.arange(1,mu+1),
    y= np.cumsum(acp.explained_variance_ratio_)
)
data = [trace]
layout = dict(title = 'variance expliquée',
              xaxis = dict(title = 'nombre de facteurs'),
              yaxis = dict(title = '% variance cumulée'),
              )
fig = dict(data=data, layout=layout)
py.iplot(fig, filename='varexp')

In [10]:
pca = PCA(n_components=40)
print(pca.fit(X))
pca.explained_variance_ratio_
X_pca = pca.fit_transform(X)
X_pca

PCA(copy=True, iterated_power='auto', n_components=40, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

array([[ 6.74821965e+02,  4.63459937e+03, -2.44289792e+02, ...,
        -9.02403648e-03, -5.75685297e-02,  1.92167603e-02],
       [ 5.43787831e+02,  4.65172408e+03, -2.63848362e+02, ...,
        -9.10565297e-03, -5.78953372e-02,  1.99371311e-02],
       [ 2.87025270e+03,  3.09256260e+03, -2.16452213e+02, ...,
        -2.73884794e-03, -1.34289157e-02,  3.88889204e-03],
       ...,
       [-2.54590708e+03,  2.44302744e+02, -4.55505134e+02, ...,
        -2.49336713e-02, -1.56824509e-02,  1.43852564e-03],
       [-2.54076502e+03,  2.52666167e+02, -4.57305806e+02, ...,
        -2.61275613e-02, -1.64184915e-02,  1.96601448e-03],
       [-2.55455967e+03,  2.74192750e+02, -4.56952123e+02, ...,
        -2.72841093e-02, -1.66434655e-02,  2.74902385e-03]])

## LINUCB (Bandit contextuel)

In [11]:
n=581012  # nombre de composantes
k=40   # nombre de features
n_a=9  # nombre d'actions

D=X_pca # data

theta=np.random.random( (n_a,k) ) + 0.00001 # le theta à prédire
choix=np.zeros(n)
recomp=np.zeros(n)
explore=np.zeros(n)
norms  =np.zeros(n)
b      =np.zeros_like(theta)
A      =np.zeros( (n_a, k,k)  )
for a in range (0,n_a):
    A[a]=np.identity(k)

A_inv = [np.identity(k) for i in range (0,n_a)]

theta_hat =np.zeros_like(theta) # features temporaires, meilleures suppositions actuelles
p      =np.zeros(n_a)
alpha   =5

In [43]:
# LinUCB

for i in range(0,n):
 
    x_i = D[i]   # vect du contexte
    
    for a in range (0,n_a):        
        theta_hat[a]  = A_inv[a].dot(b[a])      
        ta         = x_i.T.dot(A_inv[a]).dot(x_i) 
        a_upper_ci = alpha * np.sqrt(ta)     # partie supérieure de l'intervalle 
        a_mean     = theta_hat[a].dot(x_i)   # estimation actuelle de la mean
        p[a]       = a_mean + a_upper_ci     # borne sup IC
      
      
    norms[i]       = np.linalg.norm(theta_hat - theta,'fro') # convergence
    
    choix[i] = p.argmax()   #fonction de maxmisation
    
    # le resultat obtenu
    
    recomp[i] =((choix[i])==labels[i]) #la récompense
   
    # mettre à jour le vecteur d'input
    A[int(choix[i])]      += np.outer(x_i,x_i)
    A_inv[int(choix[i])]  = np.linalg.inv(A[int(choix[i])])
    b[int(choix[i])]      += recomp[i] * x_i

KeyboardInterrupt:

In [44]:
regret=(np.ones(n) - np.array(recomp))
d =regret.cumsum()
max(d)
len(d)

581012

In [34]:
recomp.cumsum()
(recomp.sum())/(len(recomp))

0.657497607622562

In [ ]:

plt.plot(recomp.cumsum())
plt.title("Recompense Cumulée ")
plt.show()


plt.plot(regret.cumsum(), color = "red")
plt.title("Regret Cumulé ")
plt.show()

In [42]:
#avec la package plotly
trace = go.Scatter(
    x= np.arange(1,581020),
    y= list(regret.cumsum())
)
data = [trace]
layout = dict(title = 'regret cumulé')
fig = dict(data=data, layout=layout)
py.iplot(fig, filename='regcum')

The draw time for this plot will be slow for all clients.